#!/usr/bin/env node
// Mirror .claude/skills/<name>/SKILL.md to other AI tool formats.
// Source of truth: .claude/skills/. Edit SKILL.md, then run `npm run skills:export`.

import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SKILLS_DIR = join(ROOT, '.claude/skills');

const header = (sourcePath) =>
  `<!-- AUTOGENERATED from ${sourcePath} - edit the source, not this file. Run \`npm run skills:export\` to regenerate. -->\n`;

function parseFrontmatter(content) {
  const m = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) return { frontmatter: {}, body: content };
  const fm = {};
  for (const line of m[1].split('\n')) {
    const kv = line.match(/^([\w-]+):\s*(.*)$/);
    if (!kv) continue;
    let val = kv[2].trim();
    if (val === 'true') val = true;
    else if (val === 'false') val = false;
    fm[kv[1]] = val;
  }
  return { frontmatter: fm, body: m[2].trim() };
}

function writeOut(path, content) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

function cleanDir(path) {
  if (existsSync(path)) rmSync(path, { recursive: true, force: true });
}

const skills = [];
for (const name of readdirSync(SKILLS_DIR).sort()) {
  const skillPath = join(SKILLS_DIR, name, 'SKILL.md');
  if (!existsSync(skillPath)) continue;
  const raw = readFileSync(skillPath, 'utf8');
  const { frontmatter, body } = parseFrontmatter(raw);
  if (!frontmatter.name || !frontmatter.description) {
    console.error(`✗ ${skillPath} is missing required frontmatter (name, description)`);
    process.exit(1);
  }
  skills.push({
    name,
    sourcePath: `.claude/skills/${name}/SKILL.md`,
    frontmatter,
    body,
  });
}

const portable = skills.filter((s) => !s.frontmatter['claude-only']);

cleanDir(join(ROOT, '.cursor/rules'));
cleanDir(join(ROOT, '.windsurf/rules'));
cleanDir(join(ROOT, '.clinerules'));
cleanDir(join(ROOT, '.continue/rules'));
cleanDir(join(ROOT, '.github/instructions'));

for (const s of portable) {
  const desc = s.frontmatter.description;

  // Cursor
  writeOut(
    join(ROOT, '.cursor/rules', `${s.name}.mdc`),
    `${header(s.sourcePath)}---
description: ${desc}
globs:
alwaysApply: false
---

${s.body}
`,
  );

  // Windsurf
  writeOut(
    join(ROOT, '.windsurf/rules', `${s.name}.md`),
    `${header(s.sourcePath)}---
trigger: model_decision
description: ${desc}
---

${s.body}
`,
  );

  // Cline
  writeOut(
    join(ROOT, '.clinerules', `${s.name}.md`),
    `${header(s.sourcePath)}# ${s.name}

_${desc}_

${s.body}
`,
  );

  // Continue
  writeOut(
    join(ROOT, '.continue/rules', `${s.name}.md`),
    `${header(s.sourcePath)}---
name: ${s.name}
description: ${desc}
---

${s.body}
`,
  );

  // GitHub Copilot
  writeOut(
    join(ROOT, '.github/instructions', `${s.name}.instructions.md`),
    `${header(s.sourcePath)}---
applyTo: "**"
description: ${desc}
---

${s.body}
`,
  );
}

// AGENTS.md - slim index used by Aider, Codex, Amp, Jules, Cody, etc.
// Each entry points at the canonical SKILL.md; agents read the full skill on demand.
// docs/agents-full.md carries the full concatenation for consumers that can't follow file paths.
const agentsIndex = portable
  .map((s) => `- **${s.name}** — ${s.frontmatter.description}\n  Full instructions: \`${s.sourcePath}\``)
  .join('\n');

writeFileSync(
  join(ROOT, 'AGENTS.md'),
  `<!-- AUTOGENERATED from .claude/skills/*/SKILL.md - edit the sources, not this file. Run \`npm run skills:export\` to regenerate. -->

# Agent Instructions

This repo has ${portable.length} task-specific skills. This file is the index — the full instructions live one file per skill under \`.claude/skills/\` (the canonical source of truth, shared with Claude Code).

**Before performing a task that matches a skill below, read that skill's \`SKILL.md\` file first and follow it.** Skill files assume repo-root-relative paths.

If you cannot open files by path, read \`docs/agents-full.md\` instead — it is the same ${portable.length} skills concatenated into one document.

## Skills

${agentsIndex}
`,
);

// docs/agents-full.md - full concatenation, fallback for consumers that can't follow paths.
const agentsBody = portable
  .map((s) => `## ${s.name}\n\n_${s.frontmatter.description}_\n\n${s.body}`)
  .join('\n\n---\n\n');

writeFileSync(
  join(ROOT, 'docs/agents-full.md'),
  `<!-- AUTOGENERATED from .claude/skills/*/SKILL.md - edit the sources, not this file. Run \`npm run skills:export\` to regenerate. -->

# Agent Instructions — full version

Fallback for tools that read \`AGENTS.md\` but cannot follow file paths. Canonical source: \`.claude/skills/*/SKILL.md\`. Prefer reading individual skills via the index in \`AGENTS.md\` — this file is large.

${agentsBody}
`,
);

// .cursorrules — root-level Cursor counterpart to CLAUDE.md (issue #213).
// Cursor injects this file into every prompt the way Claude Code reads
// CLAUDE.md; generating it from CLAUDE.md verbatim means the working
// contract cannot drift between the two tools.
const claudeMd = readFileSync(join(ROOT, 'CLAUDE.md'), 'utf8');
writeFileSync(
  join(ROOT, '.cursorrules'),
  `<!-- AUTOGENERATED from CLAUDE.md - edit CLAUDE.md, not this file. Run \`npm run skills:export\` to regenerate. -->

<!-- Cursor-specific pointers:
  - Per-task skills are mirrored to .cursor/rules/*.mdc (attached by description match).
  - To query live design-system data (tokens, components, corpus search), connect
    Cursor to the Tek MCP endpoint: copy .cursor/mcp.json.example to .cursor/mcp.json
    (gitignored) and paste the real URL from Bryan. The URL contains the access
    secret - never commit it; this repo is public.
-->

${claudeMd}`,
);

console.log(`Exported ${portable.length} skill(s) to 6 target formats + .cursorrules.`);
if (skills.length - portable.length > 0) {
  console.log(`Skipped ${skills.length - portable.length} claude-only skill(s).`);
}
