#!/usr/bin/env node
// Mirror .claude/skills/<name>/SKILL.md to other AI tool formats.
// Source of truth: .claude/skills/. Edit SKILL.md, then run `npm run skills:export`.

import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SKILLS_DIR = join(ROOT, '.claude/skills');

const header = (sourcePath) =>
  `<!-- AUTOGENERATED from ${sourcePath} - edit the source, not this file. Run \`npm run skills:export\` to regenerate. -->\n`;

function parseFrontmatter(content) {
  const m = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) return { frontmatter: {}, body: content };
  const fm = {};
  for (const line of m[1].split('\n')) {
    const kv = line.match(/^([\w-]+):\s*(.*)$/);
    if (!kv) continue;
    let val = kv[2].trim();
    if (val === 'true') val = true;
    else if (val === 'false') val = false;
    fm[kv[1]] = val;
  }
  return { frontmatter: fm, body: m[2].trim() };
}

function writeOut(path, content) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

function cleanDir(path) {
  if (existsSync(path)) rmSync(path, { recursive: true, force: true });
}

const skills = [];
for (const name of readdirSync(SKILLS_DIR).sort()) {
  const skillPath = join(SKILLS_DIR, name, 'SKILL.md');
  if (!existsSync(skillPath)) continue;
  const raw = readFileSync(skillPath, 'utf8');
  const { frontmatter, body } = parseFrontmatter(raw);
  if (!frontmatter.name || !frontmatter.description) {
    console.error(`✗ ${skillPath} is missing required frontmatter (name, description)`);
    process.exit(1);
  }
  skills.push({
    name,
    sourcePath: `.claude/skills/${name}/SKILL.md`,
    frontmatter,
    body,
  });
}

const portable = skills.filter((s) => !s.frontmatter['claude-only']);

cleanDir(join(ROOT, '.cursor/rules'));
cleanDir(join(ROOT, '.windsurf/rules'));
cleanDir(join(ROOT, '.clinerules'));
cleanDir(join(ROOT, '.continue/rules'));
cleanDir(join(ROOT, '.github/instructions'));

for (const s of portable) {
  const desc = s.frontmatter.description;

  // Cursor
  writeOut(
    join(ROOT, '.cursor/rules', `${s.name}.mdc`),
    `${header(s.sourcePath)}---
description: ${desc}
globs:
alwaysApply: false
---

${s.body}
`,
  );

  // Windsurf
  writeOut(
    join(ROOT, '.windsurf/rules', `${s.name}.md`),
    `${header(s.sourcePath)}---
trigger: model_decision
description: ${desc}
---

${s.body}
`,
  );

  // Cline
  writeOut(
    join(ROOT, '.clinerules', `${s.name}.md`),
    `${header(s.sourcePath)}# ${s.name}

_${desc}_

${s.body}
`,
  );

  // Continue
  writeOut(
    join(ROOT, '.continue/rules', `${s.name}.md`),
    `${header(s.sourcePath)}---
name: ${s.name}
description: ${desc}
---

${s.body}
`,
  );

  // GitHub Copilot
  writeOut(
    join(ROOT, '.github/instructions', `${s.name}.instructions.md`),
    `${header(s.sourcePath)}---
applyTo: "**"
description: ${desc}
---

${s.body}
`,
  );
}

// AGENTS.md - single concatenated file used by Aider, Codex, Amp, Jules, Cody, etc.
const agentsBody = portable
  .map((s) => `## ${s.name}\n\n_${s.frontmatter.description}_\n\n${s.body}`)
  .join('\n\n---\n\n');

writeFileSync(
  join(ROOT, 'AGENTS.md'),
  `<!-- AUTOGENERATED from .claude/skills/*/SKILL.md - edit the sources, not this file. Run \`npm run skills:export\` to regenerate. -->

# Agent Instructions

This file mirrors Claude Code skills under \`.claude/skills/\` for other AI agents (Aider, Codex, Amp, Jules, Cody, and any tool that reads \`AGENTS.md\`). Claude Code's \`SKILL.md\` files are the canonical source of truth.

${agentsBody}
`,
);

console.log(`Exported ${portable.length} skill(s) to 6 target formats.`);
if (skills.length - portable.length > 0) {
  console.log(`Skipped ${skills.length - portable.length} claude-only skill(s).`);
}
